#!/bin/sh

# Welcome to ysiad's laptop script
# Be prepared to turn your laptop (or desktop, no haters here)
# into an awesome development machine.

ruby \
  -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" \
  </dev/null
